import pandas as pd
import sys
# GENERATED BY AI
def parse_proper_elements(filepath: str) -> pd.DataFrame:
    rows = []
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip comment/header lines
            if not line or line.startswith('%'):
                continue
            parts = line.split()
            if len(parts) < 10:
                continue
            rows.append({
                'name':  parts[0],
                'H_mag': float(parts[1]),
                'status':     int(parts[2]),  
                'family1':     int(parts[3]), 
                'dv_fam1': float(parts[4]),  
                'near1':     (parts[5]),
                'family2':     int(parts[6]),
                'dv_fam2':     float(parts[7]),
                'near2':   float(parts[8]),
                'rescod':    (parts[9]),   
            })
    return pd.DataFrame(rows)


if __name__ == '__main__':
    filepath = sys.argv[1] if len(sys.argv) > 1 else 'proper_elements.txt'
    df = parse_proper_elements(filepath)

    out = filepath.rsplit('.', 1)[0] + '_clean.csv'
    df.to_csv(out, index=False)

    print(f"Parsed {len(df)} asteroids -> {out}")
    print(df.head())
    print(df.dtypes)